name: Metrics
on:
  schedule:
    - cron: "0 6 * * *"  # run daily at 06:00 UTC
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate profile metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # --- Who/General ---
          user: Ganainmtech
          template: classic
          base: header, repositories
          config_timezone: UTC

          # Include ALL repos you have access to (public + private)
          repositories_visibility: all
          repositories_affiliations: owner, collaborator, organization_member
          repositories_forks: no  # set to "yes" if you want forks included

          # --- Languages "slider" panel ---
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          plugin_languages_limit: 20
          plugin_languages_recent_load: 1000
          plugin_languages_analysis_timeout: 15

          # Optional: ignore filetypes that skew results
          # plugin_languages_ignored: >-
          #   vendor, node_modules, dist, build

          # Output file placed at repo root
          filename: metrics.svg
