name: Metrics
on:
  schedule:
    - cron: "0 6 * * *"  # run daily at 06:00 UTC
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate profile metrics
        uses: lowlighter/metrics@latest
        with:
          # use your classic PAT (has repo scope incl. private)
          token: ${{ secrets.METRICS_TOKEN }}

          # force it to commit back to main using that token
          committer_token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: main
          committer_message: "Update metrics.svg - [Skip GitHub Action]"

          # --- Who/General ---
          user: Ganainmtech
          template: classic
          base: header, repositories
          config_timezone: UTC

          # Repos to include
          repositories_affiliations: owner,collaborator,organization_member
          repositories_forks: no

          # --- Languages panel ---
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          plugin_languages_limit: 20
          plugin_languages_recent_load: 1000
          plugin_languages_analysis_timeout: 15

          # Output file
          filename: metrics.svg
