name: Metrics
on:
  schedule:
    - cron: "0 6 * * *"  # run daily at 06:00 UTC
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate profile metrics
        uses: lowlighter/metrics@latest
        with:
          # Auth (PAT with repo scope)
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: main
          committer_message: "Update metrics.svg - [Skip GitHub Action]"

          # Who
          user: Ganainmtech
          config_timezone: UTC

          # CORE SECTIONS TO SHOW
          template: classic
          base: ""  

    
          # LANGUAGES PLUGIN 
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_indepth: yes
          plugin_languages_limit: 20
          plugin_languages_recent_load: 1000
          plugin_languages_analysis_timeout: 15
          # Show both markup + programming in bars, and allow a lot of them:
          plugin_languages_categories: programming, markup

          # OUTPUT
          filename: metrics.svg
